name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-push:
    name: Build Docker image and push to repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to repository
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
        
      - name: Build image and push to registry
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            spoticord-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}
          
      - name: Print image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
